import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ToastProvider } from '@/components/providers/toaster-provider'
import { ConfettiProvider } from '@/components/providers/confetti-provider'
import { dark, neobrutalism } from '@clerk/themes';
import { CrispProvider } from '@/components/ui/crisp-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'OFCourse',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      appearance={{
        signIn: { baseTheme: neobrutalism },
      }}
    >
      <html lang="en">
      <CrispProvider />
        <body>{children}</body>
      </html>
    </ClerkProvider>
  )
}
